export const SET_CURRENT_LANGUAGE = "SET_CURRENT_LANGUAGE";
export const SET_CURRENT_LOCATION = "SET_CURRENT_LOCATION";
export const SET_ARE_LANGUAGES_DISABLED = "SET_ARE_LANGUAGES_DISABLED";

export const TOP_NEWS_LOADED_SUCCESSFULLY = "TOP_NEWS_LOADED_SUCCESSFULLY";
export const TOP_NEWS_FAILED_LOADING = "TOP_NEWS_FAILED_LOADING";
export const TOP_NEWS_ARE_LOADING = "TOP_NEWS_ARE_LOADING";
