export const SET_CURRENT_LANGUAGE = "SET_CURRENT_LANGUAGE";
export const SET_CURRENT_LOCATION = "SET_CURRENT_LOCATION";
export const REDIRECTED_TO_SPECIFIC_CATEGORY =
  "REDIRECTED_TO_SPECIFIC_CATEGORY";
export const SET_ARE_LANGUAGES_DISABLED = "SET_ARE_LANGUAGES_DISABLED";

export const TOP_NEWS_LOADED_SUCCESSFULLY = "TOP_NEWS_LOADED_SUCCESSFULLY";
export const TOP_NEWS_FAILED_LOADING = "TOP_NEWS_FAILED_LOADING";
export const TOP_NEWS_ARE_LOADING = "TOP_NEWS_ARE_LOADING";

export const CATEGORIES_ENTERTAINMENT_HAVE_BEEN_LOADED_SUCCESSFULLY =
  "CATEGORIES_ENTERTAINMENT_HAVE_BEEN_LOADED_SUCCESSFULLY";
export const CATEGORIES_ENTERTAINMENT_HAVE_BEEN_LOADED_WITH_ERROR =
  "CATEGORIES_ENTERTAINMENT_HAVE_BEEN_LOADED_WITH_ERROR";
export const CATEGORIES_ENTERTAINMENT_ARE_LOADING =
  "CATEGORIES_ENTERTAINMENT_ARE_LOADING";
export const CATEGORIES_GENERAL_HAVE_BEEN_LOADED_SUCCESSFULLY =
  "CATEGORIES_GENERAL_HAVE_BEEN_LOADED_SUCCESSFULLY";
export const CATEGORIES_GENERAL_HAVE_BEEN_LOADED_WITH_ERROR =
  "CATEGORIES_GENERAL_HAVE_BEEN_LOADED_WITH_ERROR";
export const CATEGORIES_GENERAL_ARE_LOADING = "CATEGORIES_GENERAL_ARE_LOADING";
export const CATEGORIES_HEALTH_HAVE_BEEN_LOADED_SUCCESSFULLY =
  "CATEGORIES_HEALTH_HAVE_BEEN_LOADED_SUCCESSFULLY";
export const CATEGORIES_HEALTH_HAVE_BEEN_LOADED_WITH_ERROR =
  "CATEGORIES_HEALTH_HAVE_BEEN_LOADED_WITH_ERROR";
export const CATEGORIES_HEALTH_ARE_LOADING = "CATEGORIES_HEALTH_ARE_LOADING";
export const CATEGORIES_SCIENCE_HAVE_BEEN_LOADED_SUCCESSFULLY =
  "CATEGORIES_SCIENCE_HAVE_BEEN_LOADED_SUCCESSFULLY";
export const CATEGORIES_SCIENCE_HAVE_BEEN_LOADED_WITH_ERROR =
  "CATEGORIES_SCIENCE_HAVE_BEEN_LOADED_WITH_ERROR";
export const CATEGORIES_SCIENCE_ARE_LOADING = "CATEGORIES_SCIENCE_ARE_LOADING";
export const CATEGORIES_SPORT_HAVE_BEEN_LOADED_SUCCESSFULLY =
  "CATEGORIES_SPORT_HAVE_BEEN_LOADED_SUCCESSFULLY";
export const CATEGORIES_SPORT_HAVE_BEEN_LOADED_WITH_ERROR =
  "CATEGORIES_SPORT_HAVE_BEEN_LOADED_WITH_ERROR";
export const CATEGORIES_SPORT_ARE_LOADING = "CATEGORIES_SPORT_ARE_LOADING";
export const CATEGORIES_TECHNOLOGY_HAVE_BEEN_LOADED_SUCCESSFULLY =
  "CATEGORIES_TECHNOLOGY_HAVE_BEEN_LOADED_SUCCESSFULLY";
export const CATEGORIES_TECHNOLOGY_HAVE_BEEN_LOADED_WITH_ERROR =
  "CATEGORIES_TECHNOLOGY_HAVE_BEEN_LOADED_WITH_ERROR";
export const CATEGORIES_TECHNOLOGY_ARE_LOADING =
  "CATEGORIES_TECHNOLOGY_ARE_LOADING";

export const SEARCH_HAS_BEEN_PERFORMED = "SEARCH_HAS_BEEN_PERFORMED";
export const SEARCH_IS_LOADING = "SEARCH_IS_LOADING";
export const SEARCH_HAS_FAILED = "SEARCH_HAS_FAILED";
